-d /home/alberto/GowinTRX/impl/gwsynthesis/GowinTRX.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/alberto/GowinTRX/src/sipeed_tang_primer_20k.cst
-cfg /home/alberto/GowinTRX/impl/pnr/device.cfg
-sdc /home/alberto/GowinTRX/src/fpga_rx.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
